import server from '../backend/mock-server'
import React from 'react'
import AppFunctional from '/AppFunctional'
import { render, fireEvent, screen } from '@testing-library/react'
import '@testing-library/jest-dom/extend-expect'